# Generated by Django 5.1.5 on 2025-01-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edidiong', '0002_about_aboutvideo_blog_blogvideo_home_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
