# Generated by Django 5.1.5 on 2025-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edidiong', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogvideo',
            name='video',
            field=models.FileField(upload_to='media/view'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='video',
            field=models.FileField(upload_to='appstore'),
        ),
    ]
